[_]
schema-version = "0.2"

[[ io.buildpacks.build.env ]]
  name  = "BP_DIRECT_PROCESS"
  value = "true"

[[ io.buildpacks.build.env ]]
  name  = "BP_NATIVE_IMAGE"
  value = "true"

[[ io.buildpacks.build.env ]]
  name  = "BP_JVM_VERSION"
  value = "25"

[[ io.buildpacks.build.env ]]
  name  = "BP_MAVEN_BUILD_ARGUMENTS"
  value = "-Pnative -Dmaven.test.skip=true package"
